# Generated by Django 3.2.7 on 2021-09-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_token', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('email_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('form_token', models.CharField(max_length=100)),
                ('form_code', models.TextField()),
                ('form_unmask', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TempModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('options', models.TextField(null=True)),
            ],
        ),
    ]
