# Generated by Django 3.2.7 on 2021-09-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_tempmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmodel',
            name='s_no',
            field=models.IntegerField(null=True),
        ),
    ]
