# Generated by Django 3.2.7 on 2021-09-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_emailtokenmodel_formtokenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtokenmodel',
            name='form_code',
            field=models.TextField(default='tiger'),
            preserve_default=False,
        ),
    ]
