# Generated by Django 3.2.7 on 2021-09-13 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_formtokenmodel_form_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormCreateModel',
        ),
    ]
