# Generated by Django 3.2.7 on 2021-09-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_delete_formcreatemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempmodel',
            name='s_no',
        ),
    ]
