# Generated by Django 3.2.7 on 2021-09-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_tempmodel_s_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtokenmodel',
            name='form_unmask',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
